# Generated by Django 2.0.6 on 2018-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_auto_20180721_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
