# Generated by Django 2.0.6 on 2018-08-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.CharField(default='', max_length=200),
        ),
    ]
