# Generated by Django 2.0.6 on 2018-08-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_auto_20180804_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.CharField(default=[], max_length=200),
        ),
    ]
